services:
  auth:
    class: PhpEarth\Stats\Auth
    arguments: ['@config']
  twig_environment:
    class: Twig_Environment
    arguments: ['@twig_loader_filesystem']
  translator.message_selector:
    class: Symfony\Component\Translation\MessageSelector
  translator.yaml_loader:
    class: Symfony\Component\Translation\Loader\YamlFileLoader
  translator:
    class: Symfony\Component\Translation\Translator
    arguments: ['%locale%', '@translator.message_selector']
    calls:
      - [addLoader, ['yaml', '@translator.yaml_loader']]
      - [addResource, ['yaml', '%project_dir%/translations/messages.%locale%.yaml', '%locale%']]
      - [setFallbackLocales, [['en']]]
  generate_command:
    class: PhpEarth\Stats\Command\GenerateCommand
    calls:
      - [setConfig, ['@config']]
      - [setTemplate, ['@twig_environment']]
      - [setAuth, ['@auth']]
      - [setReportsDir, ['%reports_dir%']]
      - [setTranslator, ['@translator']]
  clear_reports_command:
    class: PhpEarth\Stats\Command\ClearReportsCommand
    calls:
      - [setReportsRoot, ['%reports_root%']]
  offensive_words_command:
    class: PhpEarth\Stats\Command\OffensiveWordsCommand
    calls:
      - [setOffensiveWords, ["@=service('config').get('offensive_words')"]]
